### ISSUE TITLE
Going beyond 22 fields

### ISSUE THREAD

**Issue by ScalaWilliam** [nrinaudo/kantan.csv#104]
I've got a CSV of 27 fields. Defined my case class, then used `HeaderCodec.caseCodec` and at compilation it complains at both `apply` and `unapply` methods (of course it does):
![image](https://user-images.githubusercontent.com/2464813/32034894-15b1d0a4-ba48-11e7-8385-9a3995b61846.png)

Could not find related anything in the issues or documentation for Kantan.

I see a related post for Slick here: https://underscore.io/blog/posts/2016/10/11/twenty-two.html

How would you work around this problem?

**Comment by nrinaudo** [comment]
Well, quite frankly, I would not use a case class with 27 fields. Any arity over 22 is not well supported by Scala (although I understand it'll be fixed in Dotty).

Your choices are:
- split your case class into smaller ones and compose them
- if the types are homogenous, use a `List`
- if they are not, use an `HList`

**Comment by ScalaWilliam** [comment]
Sure. How would it compose with `caseCodec` though?

**Comment by nrinaudo** [comment]
There is, unfortunately, no elegant solution at the moment.
What I would do is:
* split your large case class into smaller ones
* create a `RowDecoder` instance for each case class
* create a `RowDecoder` instance for the "root" case class that delegates the work to its components.

Something like:
```scala
case class Root(foo: Foo, bar: Bar)
case class Foo(i: Int, b: Boolean)
case class Bar(f: Float, s: String)

implicit val fooDecoder: RowDecoder[Foo] = RowDecoder.decoder(0, 1)(Foo.apply)
implicit val barDecoder: RowDecoder[Bar] = RowDecoder.decoder(2, 3)(Bar.apply)
implicit val rootDecoder: RowDecoder[Root] = RowDecoder.from { row =>
  for {
    foo <- fooDecoder.decode(row)
    bar <- barDecoder.decode(row)
  } yield Root(foo, bar)
}
```

**Comment by vilinski** [comment]
Is it also possible to combine HeaderDecoders?

**Comment by Icydillic** [comment]
Hey,

I do have the same issue with the 22 fields and saw this example.
Unfortunately I have to use column header because it is not guaranteed that the column order stays the same.
I already tried to do it like this
```scala
final case class RootModel(model1: Model1, model2: Model2)
final case class Model1(value: Int)
final case class Model2(value: String)

implicit val model1Decoder: HeaderDecoder[Model1] = HeaderDecoder.decoder("Header1")(Model1)
implicit val model2Decoder: HeaderDecoder[Model2] = HeaderDecoder.decoder("Header2")(Model2)

implicit val rootDecoder: RowDecoder[RootModel] = RowDecoder.from { row =>
    for {
      model1 <- model1Decoder.decode(row)
      model2 <- model2Decoder.decode(row)
    } yield RootModel(model1, model2)
  }
```
But got stuck on the final "merge" of all pieces to one HeaderDecoder. Do you have an idea how I can achive this?

Thank you very much and best regards!
Stefan

**Comment by nrinaudo** [comment]
Sure, it's perfectly possible, even if a bit cumbersome.

First, the code:

```scala
import kantan.csv._

final case class RootModel(model1: Model1, model2: Model2)
final case class Model1(value: Int)
final case class Model2(value: String)

object RootModel {
  implicit val headerDecoder: HeaderDecoder[RootModel] = {

    // Decoders for Model1 and Model2
    implicit val model1Decoder: HeaderDecoder[Model1] = HeaderDecoder.decoder("Header1")(Model1)
    implicit val model2Decoder: HeaderDecoder[Model2] = HeaderDecoder.decoder("Header2")(Model2)

    new HeaderDecoder[RootModel] {

      override def fromHeader(header: Seq[String]) =
        // Turns the header into row decoders for Model1 and Model2
        for {
          model1D ← model1Decoder.fromHeader(header)
          model2D ← model2Decoder.fromHeader(header)
        } yield
            // Merge these two decoders into a single RowDecoder
          RowDecoder.from { row ⇒
            for {
              model1 ← model1D.decode(row)
              model2 ← model2D.decode(row)
            } yield RootModel(model1, model2)
          }

      // There's unfortunately nothing we can do if no header is provided.
      override def noHeader = sys.error("Attempting to decode without a header.")
    }
  }

}
```

Here's how you'd use it in a REPL session:

```scala
scala> import kantan.csv._
scala> import kantan.csv.ops._
scala> "Header1,Header2\n1,foo".asCsvReader[RootModel](rfc.withHeader).foreach(println _)
// Success(RootModel(Model1(1),Model2(foo)))
```

**Comment by Icydillic** [comment]
Awesome. Thank you very much!
I already saw that there is a possiblity to write a custom HeaderDecoder but the step with the .fromHeader and to use this one to get data from the raw row did not come to my mind. :o)

**Comment by InvisibleDev** [comment]
Can you please provide an example on how to write an encoder to convert to CSV with more than 22 rows? As per tutorial:
`implicit val personEncoder: RowEncoder[Person] = RowEncoder.encoder(0, 2, 1)((p: Person) ⇒ (p.id, p.name, p.age))` but tuple won't work for this case so I am confused.

**Comment by devsaik** [comment]
Hi, Trying to get this to work for Encoding scenario : 
```
case class Root(foo: Foo, bar: Bar)
case class Foo(i: Int, b: Boolean)
case class Bar(f: Float, s: String)

implicit val fooEncoder: RowEncoder[Foo] = RowEncoder.encode(0, 1)(Foo.unapply)
implicit val barEncoder: RowEncoder[Bar] = RowDecoder.encode(2, 3)(Bar.unapply)
implicit val rootEncoder: RowEncoder[Root] = RowEncoder.from { row =>
  for {
    foo <- fooEncoder.encode(row)
    bar <- barEncoder.encode(row)
  } yield Root(foo, bar)
} ``` Unable to merge  as There is a type mismatch expected NotInferred => String. 
@nrinaudo  Any help would be greatly appreciated.

**Comment by nrinaudo** [comment]
A general rule in Scala is to pay attention to the types. Your code is all over the place.

`Root` takes a `Foo` and a `Bar`. Yet your `foo` and your `bar` are both of types `Seq[String]`. So `Root(foo, bar)` makes no sense.

Additionally, `RowEncoder.from` takes ` Root => Seq[String]` and you give it a `??? => Root`, where I'm assuming you mean `???` to be a `Seq[String]` but there's no way to be sure.

I'm going to close this issue now - it's not an issue anymore but a thread of mostly unrelated requests for helps. The gitter channel is more appropriate for that.
