### ISSUE TITLE
Compile error following case_classes_as_rows.html example

### ISSUE THREAD

**Issue by janekdb** [nrinaudo/kantan.csv#111]
http://nrinaudo.github.io/kantan.csv/case_classes_as_rows.html

```
      <dependency>
        <groupId>com.nrinaudo</groupId>
        <artifactId>kantan.csv_2.11</artifactId>
        <version>0.3.1</version>
      </dependency>
```

```
[ERROR] /home/janek/projects/SomeClass.scala:261: error: object generic is not a member of package kantan.csv
[ERROR]     import kantan.csv.generic._
[ERROR]                       ^
[
```

Documentation lagging library?

**Comment by nrinaudo** [comment]
No, the documentation is correct, if maybe, in this instance, less straightforward than it could be. Check out the [documentation](http://nrinaudo.github.io/kantan.csv/shapeless.html) for the `generic` module, you're lacking a dependency.

**Comment by nrinaudo** [comment]
If adding the corresponding dependency fixes things for you, can you confirm and close this issue?

I've created #112 to address the confusing documentation.

**Comment by janekdb** [comment]
Yes, adding the dependency solved this,
```
      <dependency>
        <groupId>com.nrinaudo</groupId>
        <artifactId>kantan.csv-generic_2.11</artifactId>
        <version>0.3.1</version>
      </dependency>
```

My mistake!

**Comment by nrinaudo** [comment]
Sorry if this came out like I was blaming you. The problem was with the documentation, not you. Thanks for reporting, you're most probably not the only person with this problem, and knowing about it will help me prevent it in the future!

**Comment by janekdb** [comment]
Your responsive was perfect in everyway! Looking forward to learning more about kantan.csv.
