### ISSUE TITLE
Reading file with BOM problem

### ISSUE THREAD

**Issue by Icydillic** [nrinaudo/kantan.csv#145]
Hello,

I don't know if it is my fault or not but when I try to use the csv importer it does not work properly when the csv file has a BOM inside.
In general I did the following for importing:

```scala
import kantan.codecs.resource.bom._
import kantan.csv._
import kantan.csv.ops._

implicit val headerDecoder = HeaderDecoder.decoder(...)(tutorialModel)

val decoder = Codec.UTF8.decoder
val rawData = Source.fromResource("tutorial.csv")(decoder).mkString
rawData.asCsvReader[tutorialModel](rfc.withHeader)
```
It seems the csv importer is not able to handle the BOM if it is represented as _\uFEFF_.
It fails with the error: _Failure(TypeError: Missing header for ﻿...)_

As a workaround I will simply remove the BOM manually but regarding the docu I thought this is already supported.

Thank you very much for your help and best regards,
Stefan

**Comment by nrinaudo** [comment]
Is there any chance you could put together a minimal reproduction case - code that I can actually compile and run locally, with (possibly anonymised) sample CSV files?

**Comment by Icydillic** [comment]
Hey,

thank you for your quick answer. I uploaded a minimal example here:
[ExampleRepo](https://github.com/Icydillic/bomTest)

Does this work for you?
Best regards,
Stefan

**Comment by nrinaudo** [comment]
Ah, right. The way you've set things up is, kantan.csv is not the one that deals with the BOM. `Source` is.

Try this instead:

```scala
implicit val decoder = Codec.UTF8.decoder

getClass.getResource("/bomTest.csv").asCsvReader[BomTestModel(rfc.withHeader).foreach(println(_))
```

**Comment by Icydillic** [comment]
Ah sure you are right. Thx a lot! :o)
