### ISSUE TITLE
IntelliJ optimizes away generics import

### ISSUE THREAD

**Issue by ckchow** [nrinaudo/kantan.csv#154]
I am not sure if this is a kantan.csv issue or an IntelliJ issue, but when doing `import kantan.csv.generic._`, IntelliJ will wrongly assume that import is unused. Maybe `scala.language.implictConversions` needs to be in scope in the generic package object.

**Comment by nrinaudo** [comment]
I'm afraid that's an intellij issue. If the import is useful (ie the code won't compile without it) but intellij removes it because it doesn't see it as useful, the problem is not with the package.

**Comment by ckchow** [comment]
Ok, thanks for the reply. I'll bring it up with the scala plugin people then.
