### ISSUE TITLE
Compile error following README.md in scala.js

### ISSUE THREAD

**Issue by wizdow** [nrinaudo/kantan.csv#171]
https://github.com/nrinaudo/kantan.csv/blob/master/README.md

> import java.io.File
import kantan.csv._
import kantan.csv.ops._

>   def login(login: String, passwrd: String): Boolean = {
  def finder(ls: List[Any], ms: Right[Any, List[Any]]): Boolean ={
    if (!ls.isEmpty) {
        if (ls.head.equals(ms)) true else finder(ls.tail, ms)
    }else false
  }
(finder((new File("db\\user.csv").asCsvReader[List[String]](rfc).toList), (Right(List(login, passwrd)))))
  }

> [error] C:\Users\jmfer\Documents\Workspace\notes-scala\src\main\scala\ecomp\poli\br\Index.scala:27:35: value asCsvReader is not a member of java.io.File
[error] (finder((new File("db\\user.csv").asCsvReader[List[String]](rfc).toList), (Right(List(login, passwrd)))))
[error]                                   ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed 22 de nov de 2018 08:15:59

**Comment by nrinaudo** [comment]
`asCsvReader` takes a parameter. You're calling unary `asCsvReader`, and this does not exist. `asCsvReader[List[String]](rfc)`, on the other hand, does, as explained in the documentation and showed in the example you linked.
