### ISSUE TITLE
Scala-js not support java.io.File

### ISSUE THREAD

**Issue by ja1goncalves** [nrinaudo/kantan.csv#172]
Well, I'm trying to make a program on scala.js using the csv reader of its API, but apparently it uses the java.io.File which is not supported by the compiler ([error] Referring to non-existent class java.io.File)

**Comment by nrinaudo** [comment]
Yes, that's normal. Scala.js does not have support for `java.io.File`, so kantan.csv, in its Scala.js module, cannot support it.
