### ISSUE TITLE
Alternate kantan CSV engines not released

### ISSUE THREAD

**Issue by mihaisoloi** [nrinaudo/kantan.csv#173]
I can't find the release for `kantan.csv-jackson_2.12` for version `0.5.0` the last one seems to be `0.3.1` The same for `commons`

**Comment by nrinaudo** [comment]
Confirmed, I've no idea why that is. I'll take a look as soon as I find some time.

**Comment by nrinaudo** [comment]
I just published artifacts manually for 4.0 and 5.0, they should hit maven central in a few hours.
I *think* I understand what the problem was and will issue a corrective MR later.
