### ISSUE TITLE
Add support for Scala 2.13

### ISSUE THREAD

**Issue by nrinaudo** [nrinaudo/kantan.csv#177]

**Comment by henricook** [comment]
We'd also love this

**Comment by nrinaudo** [comment]
I’m currently stuck because not all of my dependencies support scala 2.13 yet. I think at this point the last missing one is Jon Pretty’s contextual, which I’m eventually going to time out on and rip the bits I need out.

It’s frustrating too because aside from a coule of date related things, I’ve already completed most of the work...

**Comment by seanf** [comment]
I'm guessing this is the blocker with Contextual: https://twitter.com/NicolasRinaudo/status/1152195300422868993

Thanks for your efforts, @nrinaudo!

**Comment by henricook** [comment]
Looks like contextual isn't really maintained - is it possible to ditch it, or is that very idea horrifying?

**Comment by nrinaudo** [comment]
I have ditched it. I'm stuck on something else now - `ResourceIterator` is made painful by the collection rewrite. Every other test passes, but that's problematic. Toying with the idea of dropping out of the collection API but providing conversion methods.

**Comment by nrinaudo** [comment]
Artifacts are on their way to maven central.

**Comment by seanf** [comment]
Thanks for all your efforts, @nrinaudo!

Do you know why the Scala 2.12 artifacts for 0.6.0 are missing? It looks like Travis is still [building for 2.12.10](https://travis-ci.org/nrinaudo/kantan.csv/builds/601677828), but there's no sign on Maven Central:

https://search.maven.org/search?q=g:com.nrinaudo%20kantan.csv

**Comment by nrinaudo** [comment]
Thanks for pointing that out, I have no idea what happened. Apparently *source* artifacts have been pushed, but not binary ones? What?

Something bad happened and I'm not sure what. Might have to publish 0.6.1 just as a fix...

**Comment by nrinaudo** [comment]
Looks like I managed to publish the missing JARs. They should hit maven central within the hour. I'm going back to bed and will check up on it in the morning :)

**Comment by seanf** [comment]
Thanks @nrinaudo it seems to be there now: https://search.maven.org/artifact/com.nrinaudo/kantan.csv_2.12/0.6.0/jar. Even if the search index hasn't caught up yet.
