### ISSUE TITLE
Better configurability of reader / writer engines

### ISSUE THREAD

**Issue by nrinaudo** [nrinaudo/kantan.csv#18]
Engines are currently configured the way I feel they should be by default - RFC compliant. The underlying implementation is not exposed however, which seriously limits the usefulness of external engines - what's the point of bringing in jackson csv if one cannot configure it's more esoteric features?

**Comment by Tvaroh** [comment]
@nrinaudo is it possible to use Kantan to parse just a single CSV row? I mean split `String` into `Seq[String]`. Looks like `InternalReader` which does that is private and can't be used. Does my question relate to this issue?
