### ISSUE TITLE
Microsite is empty

### ISSUE THREAD

**Issue by d10xa** [nrinaudo/kantan.csv#195]
There is no documentation on site. But gh_pages source has a lot of docs and I found the direct links with google

**Comment by nrinaudo** [comment]
This is weird, I just clicked on the link that's in the README and the other in the project description and both took me to the documentation site. Can you tell me which link, specifically, was dead for you?

**Comment by d10xa** [comment]
![IMG_20191024_140123](https://user-images.githubusercontent.com/10722234/67479560-035cf980-f667-11e9-89ef-9d1d75b5a851.jpg)
![IMG_20191024_140141](https://user-images.githubusercontent.com/10722234/67479561-035cf980-f667-11e9-9894-3f05943c6253.jpg)

**Comment by d10xa** [comment]
I do not see links to tutorials on main page

**Comment by nrinaudo** [comment]
Oh wow I see now, thanks! No idea what's going on, I'll fix it as soon as I can.

**Comment by d10xa** [comment]
Thanks

**Comment by nrinaudo** [comment]
Created a PR to fix the issue and already deployed the result, if you want to have a look. I'll clean things up later but need to go offline for a few hours.

**Comment by d10xa** [comment]
Looks good!
