### ISSUE TITLE
Optional header field

### ISSUE THREAD

**Issue by mladendinev** [nrinaudo/kantan.csv#215]
I'm processing a csv file with X number of columns which are not all mandatory i.e some of them are optional.  

```
 csv.asCsvReader[Foo](rfc.withHeader)

  object Foo {
    implicit val FooDecoder: HeaderDecoder[Foo] =
      HeaderDecoder
        .decoder(
            "Mandatory1",
            "Mandatory2",
            "Optional1"
        )(Foo.apply)
  }
```
When Optional1 is missing from the csv header and there is no data respectively for that field, I'm getting "Missing header for Optional1". How can I prevent this error and handle it properly?

**Comment by nrinaudo** [comment]
I think, at the moment, you're kind of stuck. Those are two different formats, as far as kantan.csv is concerned. You can have optional *data*, but not optional *headers*.

**Comment by Jsebayhi** [comment]
Hi, we are concidering using this lib at work, this would be a very useful feature
