### ISSUE TITLE
Consider pre-numbered aliases for `decoderXY` and `encoderXY`.

### ISSUE THREAD

**Issue by metasim** [nrinaudo/kantan.csv#24]
For the case where the case class is laid out exactly as the columns in the CSV file, it would be a nice convenience to be able to do `RowDecoder.decoder8(Foo.apply)` instead of `RowDecoder.decoder8(Foo.apply)(0, 1, 2, 3, 4, 5, 6, 7)`.

**Comment by nrinaudo** [comment]
You know, I thought I'd implemented those. Thanks for pointing out this isn't actually the case, I'll get that sorted for next release.

In the meantime, you can use the the _generic_ module that, at the cost of a [shapeless](https://github.com/milessabin/shapeless) dependency, will automatically derive encoder and decoder instances for case classes where the fields are in the exact same orders as the CSV columns. The admittedly sparse documentation has an [example](http://nrinaudo.github.io/kantan.csv/tut/parsing.html#parsing-into-case-classes).

**Comment by nrinaudo** [comment]
Right, I've got it done locally. Can't commit yet as it relies on a version of [kantan.codecs](https://github.com/nrinaudo/kantan.codecs) that is still very experimental and might yet be rolled-back, but it'll absolutely be available in 0.1.9. Thanks again for taking the time to report this!

**Comment by nrinaudo** [comment]
v0.1.9 (available as a SNAPSHOT) fixes that. Can you confirm and, if you're happy with the change, close the issue?

**Comment by nrinaudo** [comment]
I'll consider this closed for now, feel free to reopen if I'm wrong.
