### ISSUE TITLE
Overriding codecs

### ISSUE THREAD

**Issue by soujiro32167** [nrinaudo/kantan.csv#249]
Hello

I have this use case:

```scala
case class Foo(bit: Boolean)
object Foo {
  implicit val booleanAsBit: StringCodec[Boolean] = StringCodec.from({
        case "1" => Right(true)
        case "" => Right(false)
        case e => Left(DecodeError(s"expected '' or '1', got: $e"))
      })(if (_) "1" else "")
}
```

elsewhere
```scala
import kantan.csv._
import kantan.csv.ops._
import kantan.csv.generic._
import Foo

List(Foo(true)).asCsv(rfc) // expected: 1, actual: true
```

I may not understand implicit resolution well enough, but this is how I usually define codecs for Circe 🤔 
If I `import Foo._` or put the implicit directly in scope, the string does resolve to `1`. Why won't it work with the companion object?

**Comment by nrinaudo** [comment]
I'm a bit surprised at seeing `StringCodec` appear here - where does that come from? You want to define a `CellCodec`, not a `StringCodec`.

That's not the main problem though - if you fix your code to use the right type, you'll still have the same issue. Explicitly redefining the `CellCodec[Boolean]` is only useful if it's in scope when your `RowEncoder[Foo]` is defined. In your example, it's not:

- `booleanAsBit` is defined in the companion object of `Foo`.
- the compiler looks for a `CellEncoder[Boolean]` in your main.

If your `CellEncoder[Boolean]` was defined in `Foo`'s companion object, then everything would be fine. Similarly, if you explicitly imported `Foo._` in your main, everything'd work the way you expect it to.

**Comment by soujiro32167** [comment]
The `StringCodec` was just me playing around - I started with `CellCodec`. I ended up importing `Foo._`. Will revert to `CellEncoder` and try again
>  Explicitly redefining the CellCodec[Boolean] is only useful if it's in scope when your RowEncoder[Foo] is defined
Interesting, I will also try to redefined the `RowEncoder[Foo]` with the `CellCodec` in scope

Thanks a lot! This is a great library =]
