### ISSUE TITLE
Intellij red flag Ambiguous implicit complain still sbt compilation works fine

### ISSUE THREAD

**Issue by Maatary** [nrinaudo/kantan.csv#276]
So when i write a line like this

```
aFile.readCsv[List, CsvNodeDescriptor](rfc)
```

Intellij IDE complain about a possible **Ambiguous implicit** when hover over, and i compile Intellij waring is 
**No implicit arguments of type: HeaderDecoder[CsvNodeDescriptor]**. 

However when i compile with sbt i don't have the warning and everything goes fine. 

I suspect the difference between the two may have to do with options. 

Nonethless the fact that there is some sort of warning detected by intellij and that the compilation works fine with both intellij and sbt, makes me think that there is some kind of macro from Katan, that is not expanded by intellij and i see the warning. I would like it to disappear. 

Hence my questions are: 

1 - Does the problem ring a bell, if it does, any idea what might cause the warning above ?

2 - Why would Intellij complain about no implicit in scope but ultimately there is ? Where does that implicit comes from, Can i bring it in scope explicitly, or is it something expanded by a macro somewhere and therefore, it is just that Intellij is not smart enough ?

**Comment by nicolasdalsass** [comment]
If you import kantan.csv.generic._ , the decoders and encoders you need will be compiled on the fly at compile time, and IDEA will not see them (it will also mark the import as unused, which is wrong). You may also notice that compilation is quite long.

What you can do is bring those in scope explicitely by providing codecs "manually" like described here : https://nrinaudo.github.io/kantan.csv/codecs.html which you put in the companion object of your classes. Note that even though it's manual work, it's 100% trivial to do, and will also speed up your compilation times very sensibly !

**Comment by Maatary** [comment]
thank you
