### ISSUE TITLE
Consider way of keeping exceptions thrown during decoding

### ISSUE THREAD

**Issue by metasim** [nrinaudo/kantan.csv#28]
I'd like to be able to find out more details on why a decode failed. In `DecodeResult` [exceptions are swallowed](https://github.com/nrinaudo/kantan.csv/blob/master/core/src/main/scala/kantan/csv/DecodeResult.scala#L42), inhibiting this. I'd consider returning a subclass of `Failure` that wraps the exception, or just using the standard `Either` type.

**Comment by metasim** [comment]
Just saw `RowDecoder.either[A,B]`... is there a way of co-opting that to get what I want?

**Comment by nrinaudo** [comment]
Short answer: no.

Long answer: [v0.1.9](https://github.com/nrinaudo/kantan.csv/blob/v0.1.9/core/src/main/scala/kantan/csv/CsvError.scala#L9) has exactly what you want, an error type that's actually useful. If you were to attempt to parse `abcd` as an `Int` cell, for instance, you'd get a `Failure(TypeError(e))`, where `e` is the `NumberFormatException` that was thrown.

I'm not entirely sure when v0.1.9 will be ready to release, but that's what I'm working on at the moment. Let me know if this is a blocking issue for you and I'll see if I can speed things up or release an intermediate version.

**Comment by metasim** [comment]
Not a blocking issue, but would be nice long term.

Sorry I didn't say this before: This is a *fantastic* library.... CSV for Scala, done right. I've used `product-collections` and `shapeless` to do this before, and your architecture is superior.

**Comment by nrinaudo** [comment]
I agree that it'd be nice - so much so, in fact, that it's already implemented.

Glad that you enjoy kantan.csv, I'm quite happy with the direction it's headed mysef :)

Do join the gitter channel if you have questions that you're not sure qualify as issues - I'm usually around and happy to help.

**Comment by nrinaudo** [comment]
v0.1.9 (available as a SNAPSHOT) reworks error handling and should fix this. Could you check whether the new implementation matches what you had in mind and, if so, close this issue?

**Comment by nrinaudo** [comment]
I'll consider this closed for now, feel free to reopen if I'm wrong.
