### ISSUE TITLE
Why case class has implicits issue ?

### ISSUE THREAD

**Issue by LizzyMiao** [nrinaudo/kantan.csv#340]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/9492126/198178476-11ca9816-666d-4db2-a552-5f8cad6eb701.png">

I am new to scala and when I use this package follow the example in https://nrinaudo.github.io/kantan.csv/step_by_step_parsing.html it shows up above error...

Any suggestion of this?

**Comment by nrinaudo** [comment]
Sure. If you look at the documentation, there’s an entire section dedicated to decoding case classes, which you presumably haven’t gone through.
