### ISSUE TITLE
Support CSV rows with variable lengths

### ISSUE THREAD

**Issue by aroberts** [nrinaudo/kantan.csv#53]
I should be able to decode
```
1,”a”,100
2,”b"
```

into a case class shaped like
```scala
case class Foo(first: Int, second: String, third: Option[Int])
```

It works with a trailing comma before the missing field (I suspect this has to do with how the parser splits the string), and I wouldn't expect it to work unless the optional fields were at the end. Perhaps it could be as simple as switching to a `lift`-oriented approach when processing cells?

**Comment by nrinaudo** [comment]
Still needs some non-regression tests, but manual tests confirm this is fixed.
