### ISSUE TITLE
DecodeResult helpers

### ISSUE THREAD

**Issue by aroberts** [nrinaudo/kantan.csv#54]
`Result` has a bunch of awesome helpers (`fromOption`, `fromTry`, etc...) useful for handling custom cell decoding. However, they are not available on `DecodeResult`, which I found counterintuitive. It would be great if somehow these helpers were available (scope-limited appropriately, of course) on the narrowed `Result`-related types (`DecodeResult` and friends).

**Comment by nrinaudo** [comment]
Available since commit dd9033ee8fcd5f254c78d6c37d5cc11714852d3e, will soon be merged into master.
