### ISSUE TITLE
Support for cats 0.8.0

### ISSUE THREAD

**Issue by ranchoiver** [nrinaudo/kantan.csv#59]
Xor is gone in cats 0.8.0.
https://github.com/typelevel/cats/pull/1310

AFAIK kantan.csv-cats uses Xor, so migration to Either is needed.

**Comment by nrinaudo** [comment]
Yes, you're absolutely correct. I'm actually working on that as we speak, but it forces other issues to the front: I need to upgrade to more recent versions of scalacheck and discipline, which break a lot of things.

But yes, that's what's driving the next release and it's at the top of the list of priorities.

**Comment by ScalaWilliam** [comment]
Managed to simplify this down to a ScalaCheck-only problem:

```scala
import org.scalacheck.Shapeless._
import org.scalacheck._
import org.scalatest.FunSuite

class Testor extends FunSuite {

  sealed trait Or[+A, +B] extends Product with Serializable

  case class Left[A](a: A) extends Or[A, Nothing]

  case class Right[B](b: B) extends Or[Nothing, B]

  type T = Unit ⇒ Float Or Boolean

  test("Reproduce a simpler version") {
    var v: Throwable = null
    Prop.forAll { (f: T) =>
      try {
        f()
        Prop(true)
      }
      catch {
        case t: Throwable => v = t
          Prop(true)
      }
    }
    throw v
  }
}
```

**Comment by ScalaWilliam** [comment]
Managed to reduce to:

```scala
import org.scalacheck.Shapeless._
import org.scalacheck._
import org.scalatest.FunSuite
import org.scalatest.prop.GeneratorDrivenPropertyChecks

class Testor extends FunSuite with GeneratorDrivenPropertyChecks {
  sealed trait Or[+A, +B] extends Product with Serializable

  case class Left[A](a: A) extends Or[A, Nothing]

  case class Right[B](b: B) extends Or[Nothing, B]

  type T = Unit ⇒ Float Or Boolean

  test("Rep again") {
    var good: Int = 0
    var bad: Int = 0
    var caught: Throwable = null
    val frall = Prop.forAll({
      (a: T) =>
        try {
          a(())
          good = good + 1
        }
        catch {
          case e: Throwable =>
            bad = bad + 1
            caught = e
        }
        Prop(true)
    })
    frall.main(Array.empty)
    info(s"Good = ${good}, Bad = ${bad}")
    throw caught
  }
}

```

```
[info] - Rep again *** FAILED ***
[info]   org.scalacheck.Gen$RetrievalError: couldn't generate value
[info]   at org.scalacheck.Gen.loop$1(Gen.scala:57)
[info]   at org.scalacheck.Gen.doPureApply(Gen.scala:58)
[info]   at org.scalacheck.Gen.pureApply(Gen.scala:72)
[info]   at org.scalacheck.GenArities$$anonfun$function1$1$$anonfun$1.apply(GenArities.scala:15)
[info]   at Testor$$anonfun$1$$anonfun$2.apply(Testor.scala:22)
[info]   at Testor$$anonfun$1$$anonfun$2.apply(Testor.scala:20)
[info]   at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[info]   at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)
[info]   at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)
[info]   at org.scalacheck.Prop$.secure(Prop.scala:456)
[info]   ...
[info]   + Good = 99, Bad = 1 
```

**Comment by ScalaWilliam** [comment]
Changing to:

```scala
sealed trait Or[+A, +B] extends Product with Serializable
case class Left[A, B](a: A) extends Or[A, B]
case class Right[A, B](b: B) extends Or[A, B]
```

Fixes this for some reason. Do you necessarily needs the Nothing's?
Why not just use Scala's Either?

**Comment by ScalaWilliam** [comment]
Just looking at the cats, they moved it all to Scala's Either.
You can have multiple sources per Scala version, and create a type alias for your Or. Would an Either work for you?

**Comment by nrinaudo** [comment]
Thanks a lot for the test cases, I need to look into them as soon as possible.

Af or cats having moved to `Either`, that's not the point of this test. Its purpose is to use shapeless to derive automatic encoder and decoder instances for a "complex" ADT. `Or` is only ever used in this test.

**Comment by ScalaWilliam** [comment]
Good news. Reduced the test case further.

```scala
import org.scalacheck._
import org.scalacheck.derive._
import org.scalacheck.rng.Seed
import org.scalatest.FunSuite
import org.scalatest.prop.GeneratorDrivenPropertyChecks

class Testor extends FunSuite with GeneratorDrivenPropertyChecks
  with DerivedInstances {

  sealed trait Or[+A, +B]

  final case class Right[B](b: B) extends Or[Nothing, B]

  type T = Unit ⇒ Float Or Boolean

  test("Better test case") {
    val arb = implicitly[Arbitrary[T]].arbitrary
    arb.doPureApply(Gen.Parameters.default.withSize(0), seed = Seed.random(), retries = 0)
      .retrieve.get.apply(())
  }

}
```

When generation size is 0 then Gen.fail is used. I'm not sure what is the purpose of this is so far. Here's the specific line of code.

https://github.com/alexarchambault/scalacheck-shapeless/blob/master/core/shared/src/main/scala/org/scalacheck/derive/MkArbitrary.scala#L120

**Comment by ScalaWilliam** [comment]
Maybe @alexarchambault has something to say?

**Comment by alexarchambault** [comment]
@nrinaudo @ScalaWilliam Yep, this: http://stackoverflow.com/questions/40390846/deriving-arbitrary-function-instances-using-shapeless-scalacheck/40412807#40412807 :-)

**Comment by ScalaWilliam** [comment]
@nrinaudo that should be a sufficient solution

**Comment by nrinaudo** [comment]
It would be, but it doesn't actually work - yet. I might be doing something wrong. Or, alternatively, if @alexarchambault intends to fix that at the `scalacheck-shapeless` level, I've no issue with disabling these tests and re-enabling them when a fix a available.

**Comment by nrinaudo** [comment]
0.1.16-SNAPSHOT is being published as I type this and has support for cats 0.8.0.

**Comment by nrinaudo** [comment]
Note that I'm waiting on #58 before releasing 0.1.16. It's just a matter of time - I'm still waiting for a typelevel cats 2.12.0 build, which I believe is ready and just needs to be published.

**Comment by ScalaWilliam** [comment]
What resolver should I use? Doesn't work for me.

**Comment by nrinaudo** [comment]
@ScalaWilliam ah, yes, not everyone has sonatype-snapshots enabled by default :)

This is what you need:

```scala
scalaVersion := "2.11.8"

resolvers := Seq(Resolver.sonatypeRepo("snapshots"))

libraryDependencies += "com.nrinaudo" %% "kantan.csv" % "0.1.16-SNAPSHOT"
```
