### ISSUE TITLE
Support Scala.js

### ISSUE THREAD

**Issue by nrinaudo** [nrinaudo/kantan.csv#7]
Tabulate doesn't support Scala.js. It should.

**Comment by Tzbob** [comment]
Any progress on this? I'd love to see it support Scala.js!

**Comment by nrinaudo** [comment]
Well, quite frankly, none so far. I've made a few false starts, but since there has been no interest whatsoever expressed in this feature, I've sort of let it slide.

There appears to be interest now, so I'll try and get something working for the next release. No promise - I find this to be a very intimidating feature to implement - but I'll do my best!

**Comment by mlvn23** [comment]
:+1:

**Comment by nrinaudo** [comment]
Quick update on this: we're currently in dependency hell, where in order to support scala.js, kantan.codecs would need to upgrade to modern versions of scalacheck, but cats does not yet have published artifacts for these.

**Comment by antonkulaga** [comment]
It is strange because cats crosscompiles to scala/scalajs

**Comment by nrinaudo** [comment]
Yeah, the situation's changed now and I'm using the latest version of all dependencies. I should be able to start on scala.js soon, I think.
