### ISSUE TITLE
Add split / partition to CsvReader

### ISSUE THREAD

**Issue by ranchoiver** [nrinaudo/kantan.csv#77]
Would be great if there was a way to split or partition `Result`s in `CsvReader` (by `isSuccess` or `isFailure`).

Currently I use this approach:
```   
val successes = parsed.collect{
        case Success(s) => s
 }
      
 val failures = parsed.collect{
        case Failure(readError) => readError.getMessage
 }

```

**Comment by nrinaudo** [comment]
Well, `CsvReader` does not have `split` or `partition`, but `Iterator` does and `CsvReader` has a `toIterator` method (that has basically no cost). Would that be enough for your use case?

**Comment by ranchoiver** [comment]
@nrinaudo Yes, thanks!

**Comment by nrinaudo** [comment]
@ranchoiver can you confirm it works as you'd expect for your use case, and close the issue if it does?
