### ISSUE TITLE
Add ability to write single row

### ISSUE THREAD

**Issue by limansky** [nrinaudo/kantan.csv#78]
Currently it's only possible to write sequence of rows. It would be nice to be able to write a single element:
```
scala> import kantan.csv._
import kantan.csv._

scala> import kantan.csv.ops._
import kantan.csv.ops._

scala> import kantan.csv.generic._
import kantan.csv.generic._

scala> case class Foo(i: Int, s: String)
defined class Foo

scala> Foo(4, "aaa").asCsv(',')
<console>:23: error: value asCsv is not a member of Foo
       Foo(4, "aaa").asCsv(',')
```

Related problem is that "\r\n" is always added at the end of output. This might not be needed for single row.

**Comment by nrinaudo** [comment]
This is available in `0.1.18-SNAPSHOT` as an [enhancement](https://github.com/nrinaudo/kantan.csv/blob/3c762997adc57d07f7a49ea2f116752e704d7497/core/src/main/scala/kantan/csv/ops/CsvRowOps.scala) on any type that has a `RowEncoder` instance.
