### ISSUE TITLE
libraryDependencies mentioned on project page don't resolve

### ISSUE THREAD

**Issue by oschrenk** [nrinaudo/kantan.csv#82]
The project page at `http://nrinaudo.github.io/kantan.csv/` mentions installing the latest version `
0.1.18-SNAPSHOT`. This dependency doesn't resolve. Maven Central only has the stable versions `0.1.18`, `0.1.17`, and `0.1.16`.

**Comment by nrinaudo** [comment]
Absolutely. I need to republish the documentation, not sure how that happened. You want `0.1.18`. Thanks!

**Comment by nrinaudo** [comment]
This is now fixed with the release of 0.1.19. I'm closing this, but feel free to reopen it if you feel I've messed up some more.
