### ISSUE TITLE
Missing last field in a decoded row

### ISSUE THREAD

**Issue by m3nadav** [nrinaudo/kantan.csv#89]
I noticed something interesting, whenever i decode a row with a trailing space after a quoted last field it is like the field didn't exist.

The following test will fail on missing index `2`
```
      val rawRow = """ "field1","field2","field3" """
      val retVal = rawRow.asCsvReader[List[String]](rfc).next match {
        case Result.Success(parsedLine)               => parsedLine
        case Result.Failure(ParseError.NoSuchElement) => List()
        case Result.Failure(_)                        => throw ParsingError(rawRow)
      }

      retVal.head shouldEqual "field1"
      retVal(1) shouldEqual "field2"
      retVal(2) shouldEqual "field3"
```

However if you remove the trailing space of `rawRow` it will work
`val rawRow = """ "field1","field2","field3""""`

Am i missing anything or doing it wrong?

**Comment by nrinaudo** [comment]
No, I don't think you're missing anything. This looks like a bug.

I have no idea how long it will take to fix - could be minutes, could be weeks. If you're in a hurry, can I suggest you try using one of the [external engines](http://nrinaudo.github.io/kantan.csv/tut/engines.html)?

**Comment by m3nadav** [comment]
for now i trim the string before decoding it, is there another reason to use an external engine?

**Comment by nrinaudo** [comment]
Two that I can think of. Jackson is faster than... well... pretty much everything.
And both Jackson and Apache Commons CSV are more battle-tested than kantan.csv's internal parser, for obvious reasons.
