### ISSUE TITLE
Question - String vs Option[String]

### ISSUE THREAD

**Issue by vilinski** [nrinaudo/kantan.csv#99]
Hi. 
- I parse a csv row into a case class. Some values are missing. If the class field is of type `Option[String]` I get as expected `None`. What is the correct behavior if the `String` column value is missing? I naively expected I can filter the row out as some "row/cell couldn't be parsed" error, but currently I get a success with empty string, which is useless
- Is there also possibly to write some validations like `columnValue.endsWith(".jpg")` or even with regex?
Thanks.

**Comment by nrinaudo** [comment]
Regarding point 1: it's pretty unclear what you want. Could you show me a concrete example - input, decoder, expected behaviour, observed behaviour, that type of thing?

Regarding point 2: it *is* possible, but maybe a bit more convoluted than you hope. `CellDecoder` has a `filter` method, which does exactly what you need (I think). The problem though is that you appear to be using "weakly" typed data - everything is a string - and kantan.csv is very type driven.
It'd be trivial if you had a _column type / validation to perform_ association, but I don't think  you do, and without any code to work from, it's pretty hard to guess.

**Comment by vilinski** [comment]
I have to parse a very big CSV, where, for example, the [EAN](https://en.wikipedia.org/wiki/International_Article_Number) column is not always filled or just incorrect, which makes the entire row useless. Correct EAN consists of 13 digits, possibly with leading zeros. I found nothing better than to encode it as a `String` or `case class EAN(ean: String)` and not `Int`. Do you know a better way? 

```csv
ItemId;EAN;ModelName;...
12345;;
12346;5051890051134;Harry Potter
12347;0000000000000;Useless
```

Some variants of row encoding:
```scala
case class IdentifierMatch(ItemId: Int, EAN: String) // ean is "" if missing 
case class IdentifierMatch(ItemId: Int, EAN: Option[String]) // ean is None if missing
case class IdentifierMatch(ItemId: Int, EAN: EAN) // ean is EAN("") if missing

```
In the desired first case, I get this, and must filter the case classes afterwards:

```scala
List[IdentifierMatch](
    IdentifierMatch(12345, "", ...), // should be filtered out after parsing.
    IdentifierMatch(12345, "5051890051134", ...), // correct
    IdentifierMatch(12345, "0000000000000", ...), // not correct
    ...
)
```
In the second variant I filter AND transform a row into more meaningful case class.
```scala
List[IdentifierMatch](
    IdentifierMatch(12345, None, ...), // missing - should be filtered out after parsing
    IdentifierMatch(12345, Some("5051890051134"), ...), // correct, but Option is not desired
    IdentifierMatch(12345, Some("0000000000000"), ...), // not correct - should be filtered out
    ...
)
```

Hopefully it is more clear now.

**Comment by nrinaudo** [comment]
This helps a lot, and what you want is definitely possible. I'm away from a proper computer at the moment, but will write a proper answer witth code later today. The idea is to build a `CellDecoder[EAN]` by composing on the one for strings - use `filter` to fail anything that's not a valid EAN, then `map` to turn the string into an EAN.

**Comment by nrinaudo** [comment]
Right, so this seems to work (`input`, here, contains your sample CSV data):

```scala
import kantan.csv._
import kantan.csv.ops._
import kantan.csv.generic._

// Wrap EANs into a dedicated type so you can declare a decoder for it.
final case class EAN(value: String) extends AnyVal

// EAN decoder. I'm filtering on the length here, but there's nothing to prevent you from
// using whatever predicate you want.
implicit val eanDecoder: CellDecoder[EAN] =
  CellDecoder[String].filter(_.length == 13).map(EAN.apply)

final case class IdentifierMatch(itemId: Int, EAN: EAN)

input.asCsvReader[IdentifierMatch](rfc.withHeader.withCellSeparator(';')).foreach(println)
```

This yields:

```scala
Failure(TypeError: Not acceptable: '')
Success(IdentifierMatch(12346,EAN(5051890051134)))
Success(IdentifierMatch(12347,EAN(0000000000000)))
```

**Comment by vilinski** [comment]
Cool! Thank you for your time. Will definitely copy/paste your `eanDecoder` ;o) 
Still hoped there is a general option, letting the parser creating `Failure` instead of `Success("")` for all empty Strings. My scala-kungfu is too bad to make a PR for it.

**Comment by nrinaudo** [comment]
Sure you can, just apply the same principle I showed before, but filter out empty strings in the decoder.

This can't be the default though, since the empty string is definitely a valid string.
